### ISSUE TITLE
Unhandled connection reset error (reopened)

### ISSUE THREAD

**Issue by jeffswt** [xmcp/tiroFinale#6]
**Try this link, it causes invalidity every time.**

Using _tiroFinale v5.5_. It might occur again.

[http://ohmwrite.com/fp.eng?id=5ff0fb62-0643-4ff1-aaee-c737f9ffc0e0&rand=57051&ver=asynch&time=-480&referrerUrl=http%3A%2F%2Fwww.planetminecraft.com%2Fproject%2Felden---modern-house%2F&subId=&abr=true&res=1024x819&stdTime=480&fpe=3&curl=http%3A%2F%2Fwww.mediafire.com%2Fdownload%2F4atg1627oggg2cb%2FElden%2B-%2BModern%2BHouse.rar&hosted=true](http://ohmwrite.com/fp.eng?id=5ff0fb62-0643-4ff1-aaee-c737f9ffc0e0&rand=57051&ver=asynch&time=-480&referrerUrl=http%3A%2F%2Fwww.planetminecraft.com%2Fproject%2Felden---modern-house%2F&subId=&abr=true&res=1024x819&stdTime=480&fpe=3&curl=http%3A%2F%2Fwww.mediafire.com%2Fdownload%2F4atg1627oggg2cb%2FElden%2B-%2BModern%2BHouse.rar&hosted=true)

```
Traceback (most recent call last):
  File "C:\Programs\Python3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 385, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\Python3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "C:\Programs\Python3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Programs\Python3\lib\http\client.py", line 1174, in getresponse
    response.begin()
  File "C:\Programs\Python3\lib\http\client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "C:\Programs\Python3\lib\http\client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Programs\Python3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\Python3\lib\site-packages\requests\adapters.py", line 403, in send
    timeout=timeout
  File "C:\Programs\Python3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Programs\Python3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Programs\Python3\lib\site-packages\requests\packages\urllib3\packages\six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "C:\Programs\Python3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "C:\Programs\Python3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Programs\Python3\lib\http\client.py", line 1174, in getresponse
    response.begin()
  File "C:\Programs\Python3\lib\http\client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "C:\Programs\Python3\lib\http\client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Programs\Python3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Programs\tiro\finale_launcher.py", line 112, in tornado_fetcher
    with finale_request(method, url, headers, body) as res:
  File "C:\Programs\tiro\finale_launcher.py", line 100, in finale_request
    return _direct_request(method, url, headers, body)
  File "C:\Programs\tiro\finale_launcher.py", line 72, in _direct_request
    stream=True, allow_redirects=False, timeout=const.TIMEOUT,
  File "C:\Programs\Python3\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Programs\Python3\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Programs\Python3\lib\site-packages\requests\adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**Comment by xmcp** [comment]
although i don't know what the hell is the link, i can't see connection reset exception on my pc anyway.  it's not tiro's fault - it's about your network _(and probably your 2GB RAM)_.
